routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'partials.index')->name('index');

Auth::routes();

Route::resource('client', ClientController::class);

Route::view('agenda', 'agenda')->name('agenda');

Route::post('task', [TaskController::class, 'store'])
    ->name('task.store');

Route::get('/home', [HomeController::class, 'index'])
    ->name('home');

app/Models/Client.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function getAgeAttribute()
    {
        return Carbon::parse($this->attributes['birthdate'])
            ->diff(\Carbon\Carbon::now())
            ->format('%y years, %m months');
    }
}

app/Models/Expert.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Expert extends Model
{
    use HasFactory;
}

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password'
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ClientsDataTable;
use App\Models\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(ClientsDataTable $dataTable)
    {
        return $dataTable->render('clients.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Client::create($request->all());

        return redirect()->route('client.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    public function store(Request $request)
    {
        Task::create($request->all());

        return response()->json(201);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return User::all();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::create($request->all());

        return response()->json($user, 201);
    }

    /**
     * Display the specified user.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return $user;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Models\User $user
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(User $user, Request $request)
    {
        // dd($user, $request);
        $user->update($request->all());

        return response()->json($user, 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return response()->json(null, 204);
    }
}

resources/views/agenda.blade.php
@extends('layouts.guest')

@section('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/mark-your-calendar.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/pay.css') }}">    
@endsection

@section('content')
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>Agenda</h2>
        <ol>
          <li><a href="index.html">Home</a></li>
          <li>Agenda</li>
        </ol>
      </div>

    </div>
  </section>
  <!-- End Breadcrumbs -->

  <section class="inner-page">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div id="picker"></div>
            </div>

            <div class="col-md-8 d-none" id="pay">
                <form onsubmit="event.preventDefault()" class="form-card">
                    <div class="row justify-content-center mb-4 radio-group">
                        <div class="col-sm-3 col-5">
                            <div class='radio mx-auto' data-value="visa"> <img class="fit-image" src="https://i.imgur.com/OdxcctP.jpg" width="105px" height="55px"> </div>
                        </div>
                        <div class="col-sm-3 col-5">
                            <div class='radio mx-auto' data-value="master"> <img class="fit-image" src="https://i.imgur.com/WIAP9Ku.jpg" width="105px" height="55px"> </div>
                        </div>
                        <div class="col-sm-3 col-5">
                            <div class='radio mx-auto' data-value="paypal"> <img class="fit-image" src="https://i.imgur.com/cMk1MtK.jpg" width="105px" height="55px"> </div>
                        </div> <br>
                    </div>

                    <div class="row justify-content-center">
                        <div class="col-12">
                            <div class="input-group"> <input type="text" name="Name" placeholder="John Doe"> <label>Name</label> </div>
                        </div>
                    </div>

                    <div class="row justify-content-center">
                        <div class="col-12">
                            <div class="input-group"> <input type="text" id="cr_no" name="card-no" placeholder="0000 0000 0000 0000" minlength="19" maxlength="19"> <label>Card Number</label> </div>
                        </div>
                    </div>

                    <div class="row justify-content-center">
                        <div class="col-12">
                            <div class="row">
                                <div class="col-6">
                                    <div class="input-group"> <input type="text" id="exp" name="expdate" placeholder="MM/YY" minlength="5" maxlength="5"> <label>Expiry Date</label> </div>
                                </div>
                                <div class="col-6">
                                    <div class="input-group"> <input type="password" name="cvv" placeholder="&#9679;&#9679;&#9679;" minlength="3" maxlength="3"> <label>CVV</label> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row justify-content-center">
                        <div class="col-md-12"> 
                            <input type="submit" value="Pay" class="btn btn-success btn-block">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
  </section>
@endsection

@section('js')
    <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{{ asset('assets/js/mark-your-calendar.js') }}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script type="text/javascript">
        (function($) {
        $('#picker').markyourcalendar({
            availability: [
            ['1:00', '2:00', '3:00', '4:00', '5:00'],
            ['2:00'],
            ['3:00'],
            ['4:00'],
            ['5:00'],
            ['6:00'],
            ['7:00']
            ],
            startDate: new Date(),
            onClick: function(ev, data) {
                // data is a list of datetimes
                var d = data[0].split(' ')[0];
                var t = data[0].split(' ')[1];
                $('#selected-date').html(d);
                $('#selected-time').html(t);
                $('#pay').removeClass('d-none');
            },
            onClickNavigator: function(ev, instance) {
                var arr = [
                    [
                    ['4:00', '5:00', '6:00', '7:00', '8:00'],
                    ['1:00', '5:00'],
                    ['2:00', '5:00'],
                    ['3:30'],
                    ['2:00', '5:00'],
                    ['2:00', '5:00'],
                    ['2:00', '5:00']
                    ],
                    [
                    ['2:00', '5:00'],
                    ['4:00', '5:00', '6:00', '7:00', '8:00'],
                    ['4:00', '5:00'],
                    ['2:00', '5:00'],
                    ['2:00', '5:00'],
                    ['2:00', '5:00'],
                    ['2:00', '5:00']
                    ],
                    [
                    ['4:00', '5:00'],
                    ['4:00', '5:00'],
                    ['4:00', '5:00', '6:00', '7:00', '8:00'],
                    ['3:00', '6:00'],
                    ['3:00', '6:00'],
                    ['3:00', '6:00'],
                    ['3:00', '6:00']
                    ],
                    [
                    ['4:00', '5:00'],
                    ['4:00', '5:00'],
                    ['4:00', '5:00'],
                    ['4:00', '5:00', '6:00', '7:00', '8:00'],
                    ['4:00', '5:00'],
                    ['4:00', '5:00'],
                    ['4:00', '5:00']
                    ],
                    [
                    ['4:00', '6:00'],
                    ['4:00', '6:00'],
                    ['4:00', '6:00'],
                    ['4:00', '6:00'],
                    ['4:00', '5:00', '6:00', '7:00', '8:00'],
                    ['4:00', '6:00'],
                    ['4:00', '6:00']
                    ],
                    [
                    ['3:00', '6:00'],
                    ['3:00', '6:00'],
                    ['3:00', '6:00'],
                    ['3:00', '6:00'],
                    ['3:00', '6:00'],
                    ['4:00', '5:00', '6:00', '7:00', '8:00'],
                    ['3:00', '6:00']
                    ],
                    [
                    ['3:00', '4:00'],
                    ['3:00', '4:00'],
                    ['3:00', '4:00'],
                    ['3:00', '4:00'],
                    ['3:00', '4:00'],
                    ['3:00', '4:00'],
                    ['4:00', '5:00', '6:00', '7:00', '8:00']
                    ]
                ]
                var rn = Math.floor(Math.random() * 10) % 7;
                instance.setAvailability(arr[rn]);
            }
        });
        })(jQuery);
    </script>
    <script type="text/javascript" src="{{ asset('assets/js/pay.js') }}"></script>
@endsection

resources/views/clients/create.blade.php
@extends('layouts.guest')

@section('content')
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>Register new client</h2>
        <ol>
          <li><a href="index.html">Home</a></li>
          <li>Register</li>
        </ol>
      </div>

    </div>
  </section>
  <!-- End Breadcrumbs -->

  <section class="inner-page">
    <div class="container" style="height: 60vh;">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card border-0">
    
                    <div class="card-body">
                        <form method="POST" action="{{ route('client.store') }}">
                            @csrf
    
                            <div class="form-group row">
                                <label for="username" class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>
    
                                <div class="col-md-6">
                                    <input id="username" type="text" class="form-control @error('username') is-invalid @enderror" name="username" value="{{ old('username') }}" required autocomplete="username" autofocus>
    
                                    @error('username')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>
    
                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">
    
                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                            <div class="form-group row">
                                <label for="birthdate" class="col-md-4 col-form-label text-md-right">{{ __('Birthdate') }}</label>
    
                                <div class="col-md-6">
                                    <input id="birthdate" type="date" class="form-control @error('birthdate') is-invalid @enderror" name="birthdate" required autocomplete="birthdate">
    
                                    @error('birthdate')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-form-label col-sm-4 text-right">Gender</label>
                                <div class="col-sm-6">
                                  <div class="form-check">
                                    <input class="form-check-input" type="radio" name="gender" value="1" checked>
                                    <label class="form-check-label" for="gridRadios1">
                                      Male
                                    </label>
                                  </div>
                                  <div class="form-check">
                                    <input class="form-check-input" type="radio" name="gender" value="0">
                                    <label class="form-check-label" for="gridRadios2">
                                      Female
                                    </label>
                                  </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="job" class="col-md-4 col-form-label text-md-right">{{ __('Job') }}</label>
    
                                <div class="col-md-6">
                                    <input id="job" type="text" class="form-control @error('job') is-invalid @enderror" name="job" value="{{ old('job') }}" required autocomplete="job" autofocus>
    
                                    @error('job')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="location" class="col-md-4 col-form-label text-md-right">{{ __('Location') }}</label>
    
                                <div class="col-md-6">
                                    <input id="location" type="text" class="form-control @error('location') is-invalid @enderror" name="location" value="{{ old('location') }}" required autocomplete="location" autofocus>
    
                                    @error('location')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
    
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </section>
@endsection

resources/views/clients/index.blade.php
@extends('layouts.guest')

@section('content')
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>Clients</h2>
        <ol>
          <li><a href="index.html">Home</a></li>
          <li>Clients</li>
        </ol>
      </div>

    </div>
  </section>
  <!-- End Breadcrumbs -->

  <section class="inner-page">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 table-responsive">
                {{ $dataTable->table() }}
            </div>
        </div>
    </div>
  </section>
@endsection

@push('scripts')
    {{$dataTable->scripts()}}
@endpush

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ config('app.name', 'Laravel') }}</title>

        @include('partials.styles')

        @yield('css')
    </head>

    <body>

        <div id="app">

            @include('partials.header')

            <main id="main" >

                @yield('content')

            </main><!-- End #main -->   

            @include('partials.footer')

            @include('partials.scripts')

        </div>

        <script src="{{ mix('js/app.js') }}"></script>
        <script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
        @stack('scripts')
        @yield('js')

    </body>
</html>

resources/views/partials/footer.blade.php
<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="container">
    <h3>Andrade y asociados</h3>
    <p>Et aut eum quis fuga eos sunt ipsa nihil. Labore corporis magni eligendi fuga maxime saepe commodi placeat.</p>
    <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
    </div>
    <div class="copyright">
        &copy; Copyright 
        <strong><span>Andrade y asociados</span></strong>. 
        All Rights Reserved
    </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top">
    <i class="ri-arrow-up-line"></i>
</a>

resources/views/partials/header.blade.php
<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center  header-transparent ">
    <div class="container d-flex align-items-center">

        <div class="logo mr-auto">
            <h1 class="text-light"><a href="{{ route('index') }}">Andrade y asociados</a></h1>
        </div>

        <nav class="nav-menu d-none d-lg-block">
            <ul>
                <li class="{{ Request::is('/') ? 'active' : '' }}">
                    <a href="{{ route('index') }}">Home</a>
                </li>
                <li>
                    <a href="#about">About</a>
                </li>
                <li>
                    <a href="#services">Services</a>
                </li>
                <li>
                    <a href="#contact">Contact</a>
                </li>
                <li class="drop-down {{ Request::is('client*') ? 'active' : '' }}">
                    <a href="#">Clients</a>
                    <ul>
                        <li><a href="{{ route('client.index') }}">All Clients</a></li>
                        <li><a href="{{ route('client.create') }}">New Client</a></li>
                    </ul>
                </li>
                <li class="{{ Request::is('agenda') ? 'active' : '' }}">
                    <a href="{{ route('agenda') }}">Agenda</a>
                </li>
                <li class="drop-down {{ Request::is('login', 'register') ? 'active' : '' }}">
                    <a href="#">Login / Register</a>
                    <ul>
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    </ul>
                </li>
            </ul>
        </nav><!-- .nav-menu -->

    </div>
</header><!-- End Header -->

resources/views/partials/scripts.blade.php
<!-- Vendor JS Files -->
<script src="{{ asset("assets/vendor/jquery/jquery.min.js") }}"></script>
<script src="{{ asset("assets/vendor/bootstrap/js/bootstrap.bundle.min.js") }}"></script>
<script src="{{ asset("assets/vendor/jquery.easing/jquery.easing.min.js") }}"></script>
<script src="{{ asset("assets/vendor/php-email-form/validate.js") }}"></script>
<script src="{{ asset("assets/vendor/isotope-layout/isotope.pkgd.min.js") }}"></script>
<script src="{{ asset("assets/vendor/venobox/venobox.min.js") }}"></script>
<script src="{{ asset("assets/vendor/owl.carousel/owl.carousel.min.js") }}"></script>
<script src="{{ asset("assets/vendor/aos/aos.js") }}"></script>

<!-- Template Main JS File -->
<script src="{{ asset("assets/js/main.js") }}"></script>